name: Home Assistant Release Monitoring

on:
  schedule:
    # Freitag 09:00 deutsche Zeit (mehr Zeit für API-Propagation)
    - cron: '0 7 * * 5' # Freitag 07:00 UTC (09:00 CET/CEST)
    # Samstag 09:00 deutsche Zeit (Fallback für verpasste Releases)
    - cron: '0 7 * * 6' # Samstag 07:00 UTC (09:00 CET/CEST)
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  check-ha-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Time guard (run at 09:00 German time, Fri+Sat or manual)
        id: timecheck
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "🔧 Manual workflow dispatch - running immediately"
          else
            HOUR=$(TZ=Europe/Berlin date +'%H')
            DAY=$(TZ=Europe/Berlin date +'%u')  # 5=Freitag, 6=Samstag
            echo "Local hour in Europe/Berlin: $HOUR, Day: $DAY"
            if [ "$HOUR" = "09" ] && ([ "$DAY" = "5" ] || [ "$DAY" = "6" ]); then
              echo "should_run=true" >> $GITHUB_OUTPUT
              echo "✅ Running HA monitoring at optimal time"
            else
              echo "should_run=false" >> $GITHUB_OUTPUT
              echo "⏰ Not the scheduled time for HA monitoring"
            fi
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
        if: steps.timecheck.outputs.should_run == 'true'

      - name: Run HA release check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        if: steps.timecheck.outputs.should_run == 'true'
        run: |
          python .github/scripts/check_ha_releases.py

      - name: Commit state update (if changed)
        if: steps.timecheck.outputs.should_run == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "ha: record processed Home Assistant release"
          file_pattern: .github/ha_release_state.json


