name: HACS Validation

on:
  pull_request_target:
  schedule:
    - cron: '0 3 * * 5'  # CET → 05:00 Europe/Berlin
    - cron: '0 4 * * 5'  # CEST → 05:00 Europe/Berlin
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Zeitgesteuerte Ausführung (nur 05:00 Europa/Berlin bei Zeitplan)
        if: github.event_name == 'schedule'
        id: timecheck
        run: |
          HOUR=$(TZ=Europe/Berlin date +'%H')
          echo "Lokale Uhrzeit in Europa/Berlin: $HOUR"
          if [ "$HOUR" = "05" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: HACS-Validierung
        if: ${{ github.event_name != 'schedule' || (github.event_name == 'schedule' && steps.timecheck.outputs.should_run == 'true') }}
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands images


