name: Repository-Labels einrichten

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  ensure-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Standard-Labels sicherstellen
        uses: actions/github-script@v7
        with:
          script: |
            const required = [
              { name: 'dependencies', color: '0366d6', description: 'Abhängigkeitsaktualisierungen' },
              { name: 'python', color: '2b67c6', description: 'Python-bezogen' },
              { name: 'github-actions', color: '6f42c1', description: 'CI/CD-Updates' },
              { name: 'home-assistant', color: '00aaff', description: 'Home Assistant-bezogen' },
              { name: 'breaking-changes', color: 'd73a4a', description: 'Breaking Changes erkannt' }
            ];

            async function upsert(label) {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                });
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description,
                });
                core.info(`Label aktualisiert: ${label.name}`);
              } catch (e) {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description,
                });
                core.info(`Label erstellt: ${label.name}`);
              }
            }

            for (const lbl of required) {
              await upsert(lbl);
            }

