name: Setup Repository Topics

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ensure-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure required topics for HACS
        uses: actions/github-script@v7
        with:
          script: |
            const required = ["hacs", "home-assistant", "integration"];
            const { data } = await github.rest.repos.getAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const current = new Set(data.names || []);
            for (const t of required) current.add(t);
            const names = Array.from(current);
            await github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names,
            });
            core.info(`Topics set: ${names.join(", ")}`);


