name: Auto-Merge Wöchentlicher Deps PR (Patch/Minor)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-weekly:
    if: github.event.pull_request.head.ref == 'chore/weekly-deps-update'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v5

      - name: Auto-Merge aktivieren
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          echo "Aktiviere Auto-Merge für Weekly Deps PR #${PR_NUMBER}..."
          gh pr merge ${PR_NUMBER} \
            --auto \
            --squash \
            --delete-branch \
            --body "Automatisch zusammengeführt nach erfolgreichen Required Checks." \
            --subject "deps: wöchentliche Abhängigkeitsaktualisierung (automatisch)"
          
          echo "Auto-Merge für Weekly Deps PR #${PR_NUMBER} aktiviert"
