name: Auto-Merge Wöchentlicher Deps PR (Patch/Minor)

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-weekly:
    if: github.actor == 'github-actions[bot]' && github.event.pull_request.head.ref == 'chore/weekly-deps-update'
    runs-on: ubuntu-latest
    steps:
      - name: Wöchentlichen Deps PR automatisch genehmigen
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Automatische Genehmigung wöchentlicher patch/minor Abhängigkeitsaktualisierung"

      - name: Statuschecks beobachten
        id: wait-checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checks ${{ github.event.pull_request.number }} --watch

      - name: Merge-Status abrufen
        id: pr-state
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          merged=$(gh pr view ${{ github.event.pull_request.number }} --json merged --jq '.merged')
          echo "merged=${merged}" >> "${GITHUB_OUTPUT}"

      - name: PR mergen und Branch löschen
        if: steps.pr-state.outputs.merged != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --body "Automatisch zusammengeführt nach erfolgreichen Statuschecks." --subject "deps: wöchentliche Abhängigkeitsaktualisierung (automatisch)"
