name: Auto-Merge Wöchentlicher Deps PR (Patch/Minor)

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-weekly:
    if: github.actor == 'github-actions[bot]' && github.event.pull_request.head.ref == 'chore/weekly-deps-update'
    runs-on: ubuntu-latest
    steps:
      - name: Wöchentlichen Deps PR automatisch genehmigen
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Automatische Genehmigung wöchentlicher patch/minor Abhängigkeitsaktualisierung"

      - name: Auto-Merge aktivieren (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash


