name: Auto-Merge Weekly Deps PR (Patch/Minor)

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge-weekly:
    if: github.actor == 'github-actions[bot]' && github.event.pull_request.head.ref == 'chore/weekly-deps-update'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve weekly deps PR
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approve weekly patch/minor dependency update"

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash


